# encoding: utf-8

"""
This file is auto-generated by Ansible, do not modify it.
"""

from project.settings import *

# Database
{% if django_database == 'postgres' %}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',               # Set to empty string for localhost.
        'PORT': '',               # Set to empty string for default.
    }
}
{% endif %}

# Email
{% if django_debug %}
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
{% endif %}

# Debug
DEBUG = {{ django_debug }}

# Security
ALLOWED_HOSTS = ["{{ django_domain }}"]
SECRET_KEY = "{{ secret_key }}"

# Static
STATIC_ROOT = "{{ dir_static }}"

# Media
MEDIA_ROOT = "{{ dir_media }}"
MEDIA_URL = '/media/'
