# Generated by Django 2.0 on 2018-04-03 10:12

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='wsn_metadat_tags_43d4c4_gin'),
        ),
        migrations.AddField(
            model_name='frame',
            name='metadata',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='wsn.Metadata'),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('time', 'metadata')},
        ),
    ]
