# Generated by Django 2.0.4 on 2018-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='A116_panel_tmpr',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='BEC_99_99_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='CS650PERIOD_99_99_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='CS650VRATIO_99_99_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='CXTLA_tilt_X',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='CXTLA_tilt_Y',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1DRIFTmax_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1DRIFTmean_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1DRIFTmin_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1DRIFTstd_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1DRIFTsum_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1WSmax_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1WSmean_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC1WSmin_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2DRIFTmax_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2DRIFTmean_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2DRIFTmin_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2DRIFTstd_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2DRIFTsum_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2WSmax_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2WSmean_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FC2WSmin_16_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FTPResult_Biomet',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='FTPResult_StationStatus',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='LWIN_6_14_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='LWOUT_6_15_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='METNOR_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='METNOS_99_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='PA_4_2_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='PERMITTIVITY_99_99_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='RECORD',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='RH_19_3_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='RH_19_3_1_2_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='Rl_down_meas',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='Rl_up_meas',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SHF_6_37_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SHF_6_37_2_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SHF_99_37_1_1_2',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SHF_99_37_2_1_2',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SURFACETEMP_2_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SWC_12_36_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SWIN_6_10_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='SWOUT_6_11_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TA_2_1_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TA_2_1_1_2_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TSS_2_99_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TS_2_38_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TS_2_38_2_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TS_2_38_3_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='T_K_nr',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='T_nr',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='VIN_18_39_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='WD_20_35_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='WS_16_33_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='batt_CR6',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='panel_tmpr',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='received',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
