# Generated by Django 2.0.4 on 2018-05-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0003_auto_20180511_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={},
        ),
    ]
