# Generated by Django 2.1.2 on 2018-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0005_auto_20181030_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='process_time',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
