# Generated by Django 2.1.2 on 2018-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0007_frame_pulse_cnr4_tot'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='buff_depth',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
