# Generated by Django 2.1.2 on 2018-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0008_frame_buff_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='LicorOn',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='PowLicor',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='shf_cal_on_f',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='sw12_1_state',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
