# Generated by Django 2.1.2 on 2018-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0010_frame_bat'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='RH1_19_3_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='TA1_2_1_1_1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
