# Generated by Django 2.1.2 on 2018-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0013_auto_20181129_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='name',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
