# Generated by Django 2.1.2 on 2018-11-29 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0014_metadata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('name', 'tags')},
        ),
    ]
