# Generated by Django 2.1.2 on 2018-12-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0015_auto_20181129_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('metadata', 'time', 'frame')},
        ),
    ]
