# Generated by Django 2.1.7 on 2019-05-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0017_frame_frame_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='metadata',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='wsn.Metadata'),
        ),
    ]
