# Generated by Django 2.2.6 on 2019-11-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0019_auto_20191107_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='inserted',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
