# Generated by Django 2.2.6 on 2019-11-08 18:43

from django.db import migrations, models
import wsn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0020_frame_inserted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='inserted',
            field=models.IntegerField(default=wsn.models.epoch, editable=False, null=True),
        ),
    ]
