# Generated by Django 6.1.2 on 2026-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsn', '0023_auto_20210902_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('pk', models.CompositePrimaryKey('name', 'path', blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('path', models.CharField(editable=False, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', editable=False, max_length=8)),
                ('error', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'path'],
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['status'], name='importfile_status_pending')],
            },
        ),
    ]
