dist: bionic
language: python
python:
  - "3.6"
  - "3.7"

services: postgresql
addons:
  postgresql: "10"

install:
  - pip install ansible
  - psql -c 'create database wsn;' -U postgres
  - ansible-playbook -i ansible/hosts ansible/travis.yml

script: pytest
