dist: xenial
language: python
python: 3.6

services: postgresql

install:
  - pip install ansible
  - git submodule init
  - git submodule update
  - ansible-playbook -i ansible/hosts ansible/travis.yml

script: pytest
