# ruff: noqa: F403 F405

#
# Settings load order:
#
# 1. settings_django.py  : Defaults from Django (do not edit)
# 2. settings_ansible.py : Generated by Ansible (do not edit/commit)
#                          Includes the settings from the mods list
# 3. settings.py         : The project specific settings (this file)
# 4. settings_local.py   : Local settings (do not commit)
#

import os
import socket

# Project
from project.settings_ansible import *


# Applications
INSTALLED_APPS += [
    # Requirements
    'clickhouse_backend',
    'drf_spectacular',
    'rangefilter',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_api_key',
    # Project
    'api',
    'ch',
    'qc',
    'wsn',
]

# Static files
STATICFILES_DIRS.append(BASE_DIR / 'project' / 'static')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    'formatters': {
        "default": {
            "()": "django.utils.log.ServerFormatter",
            'style': '{',
            'fmt': '[{asctime}] {levelname} {name} {message}',
            'datefmt': '%d/%m/%Y:%H:%M:%S %z',  # 22/Mar/2025:10:05:09 +0100
        },
    },
    'handlers': {
        "stdout": {
            "class": "logging.StreamHandler",
            'stream': 'ext://sys.stdout',
            "formatter": "default",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "ERROR",
        },
    },
    'loggers': {
        # Catch everything, log to standard output
        '': {
            'handlers': ['stdout'],
            'level': 'INFO',
        },
        # Send emails to admins for errors
        "django": {
            "handlers": ["mail_admins"],
            "level": "INFO",
            'propagate': True,
        },
    },
}

if 'LOGGING_UVICORN' in locals():
    for key, value in LOGGING_UVICORN.items():
        LOGGING[key] = value


# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Emails
ADMINS = (
    ('J. David Ibanez', 'jdavid.ibp@gmail.com'),
)
MANAGERS = ADMINS

fqdn = socket.getfqdn()
DEFAULT_FROM_EMAIL = 'webmaster@' + fqdn
SERVER_EMAIL = 'root@' + fqdn

# Databases: PostgreSQL and ClickHouse
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'wsn',
        'USER': 'wsn',
        'PASSWORD': os.environ.get('WSN_POSTGRESQL_PASSWORD', ''),
        'HOST': '',
        'PORT': '',
    },
    'clickhouse': {
        "ENGINE": "clickhouse_backend.backend",
        "NAME": "wsn",
        "HOST": "localhost",
        "USER": os.environ.get('WSN_CLICKHOUSE_USER', 'default'),
        "PASSWORD": os.environ.get('WSN_CLICKHOUSE_PASSWORD', ''),
    },
}

# GitHub Actions uses service containers, which require TCP connections
if os.environ.get('CI'):
    DATABASES['default']['HOST'] = 'localhost'
    DATABASES['default']['PORT'] = '5432'
    DATABASES['clickhouse']['HOST'] = 'localhost'
DATABASE_ROUTERS = ["project.dbrouters.ClickHouseRouter"]

# If not defined the producer will hang forever when the broker is not
# available. Iridium requires the callback to run in less than 3s.
# https://github.com/celery/celery/issues/4296#issuecomment-444104961
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'interval_start': 0,  # Retry immediately (1st retry)
    'interval_step': 0.5, # Add .5s to every subsequent retry
    'interval_max': 3,    # Max 3s
    'max_retries': 3,     # 0 + 0.5 + 1 = 1.5s
}

# To be extra sure the messages are not handled by a worker from another
# project: do not use the default 'celery' queue.
CELERY_TASK_ROUTES = {
    '*': {'queue': 'celery_wsn'},
}

# Celery singleton
CELERY_SINGLETON_BACKEND_URL = 'redis://localhost:6379/wsn'

# Task options (not standard)
CELERY_TASK_MAX_RETRIES = None # Retry forever

# ClickHouse
CLICKHOUSE_HOST = 'localhost'
CLICKHOUSE_USER = 'default'
CLICKHOUSE_PASSWORD = ''
CLICKHOUSE_NAME = 'wsn'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication', # For the browsable views
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'PAGE_SIZE': 100,
    'STRICT_JSON': False,
}

# wsn: folder where frames are archived
WSN_DATA_DIR = BASE_DIR / 'var' / 'data'
WSN_CIPHER_KEY = os.environ.get('WSN_CIPHER_KEY', None)

# Local settings, these should not be committed
try:
    from .settings_local import *
except ImportError:
    pass
