# Generated by Django 4.2.28 on 2026-03-26 18:12

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0004_myr1hfdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myr2Hfdata',
            fields=[
                ('timestamp', clickhouse_backend.models.DateTime64Field(db_column='TIMESTAMP', precision=3, primary_key=True, serialize=False)),
                ('ts', clickhouse_backend.models.Float64Field(db_column='Ts')),
                ('ux', clickhouse_backend.models.Float64Field(db_column='Ux')),
                ('uy', clickhouse_backend.models.Float64Field(db_column='Uy')),
                ('uz', clickhouse_backend.models.Float64Field(db_column='Uz')),
                ('h2o', clickhouse_backend.models.Float64Field(db_column='H2O')),
                ('h2o_dry', clickhouse_backend.models.Float64Field(db_column='H2O_dry')),
                ('co2', clickhouse_backend.models.Float64Field(db_column='CO2')),
                ('co2_dry', clickhouse_backend.models.Float64Field(db_column='CO2_dry')),
                ('t_in', clickhouse_backend.models.Float64Field(db_column='T_in')),
                ('t_out', clickhouse_backend.models.Float64Field(db_column='T_out')),
                ('ptotal', clickhouse_backend.models.Float64Field(db_column='Ptotal')),
                ('agc', clickhouse_backend.models.Float64Field(db_column='AGC')),
                ('ch4_mmol_m3', clickhouse_backend.models.Float64Field(db_column='CH4_mmol_m3')),
                ('ch4_umol_mol', clickhouse_backend.models.Float64Field(db_column='CH4_umol_mol')),
                ('ch4_temperature', clickhouse_backend.models.Float64Field(db_column='CH4_Temperature')),
                ('ch4_pressure', clickhouse_backend.models.Float64Field(db_column='CH4_Pressure')),
                ('ch4_signal_strength', clickhouse_backend.models.Float64Field(db_column='CH4_Signal_Strength')),
            ],
            options={
                'db_table': 'myr1_HFData',
                'managed': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
