# Generated by Django 4.2.28 on 2026-03-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0005_myr2hfdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myr2hfdata',
            table='myr2_HFData',
        ),
    ]
