# Generated by Django 4.2.28 on 2026-05-21 10:06

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0007_myr1postproc_myr2postproc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinsefeteneHfdata',
            fields=[
                ('timestamp', clickhouse_backend.models.DateTime64Field(db_column='TIMESTAMP', precision=3, primary_key=True, serialize=False)),
                ('agc', clickhouse_backend.models.Float64Field(db_column='AGC')),
                ('co2', clickhouse_backend.models.Float64Field(db_column='CO2')),
                ('co2_dry', clickhouse_backend.models.Float64Field(db_column='CO2_dry')),
                ('h2o', clickhouse_backend.models.Float64Field(db_column='H2O')),
                ('h2o_dry', clickhouse_backend.models.Float64Field(db_column='H2O_dry')),
                ('ptotal', clickhouse_backend.models.Float64Field(db_column='Ptotal')),
                ('sos', clickhouse_backend.models.Float64Field(db_column='SOS')),
                ('t_in', clickhouse_backend.models.Float64Field(db_column='T_in')),
                ('t_out', clickhouse_backend.models.Float64Field(db_column='T_out')),
                ('ux', clickhouse_backend.models.Float64Field(db_column='Ux')),
                ('uy', clickhouse_backend.models.Float64Field(db_column='Uy')),
                ('uz', clickhouse_backend.models.Float64Field(db_column='Uz')),
            ],
            options={
                'db_table': 'finsefetene_HFData',
                'managed': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
