# Generated by Django 6.0 on 2026-07-16

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0009_finsefetenepostproc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myr1HfdataSonic',
            fields=[
                ('timestamp', clickhouse_backend.models.DateTime64Field(db_column='TIMESTAMP', precision=3, primary_key=True, serialize=False)),
                ('ux', clickhouse_backend.models.Float64Field(db_column='Ux')),
                ('uy', clickhouse_backend.models.Float64Field(db_column='Uy')),
                ('uz', clickhouse_backend.models.Float64Field(db_column='Uz')),
                ('ts', clickhouse_backend.models.Float64Field(db_column='Ts')),
            ],
            options={
                'db_table': 'myr1_HFData_sonic',
                'managed': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS myr1_HFData_sonic (
                `TIMESTAMP` DateTime64(3, 'UTC'),
                `Ux` Float64 DEFAULT nan,
                `Uy` Float64 DEFAULT nan,
                `Uz` Float64 DEFAULT nan,
                `Ts` Float64 DEFAULT nan
            )
            ENGINE = ReplacingMergeTree()
            PARTITION BY toYYYYMM(TIMESTAMP)
            ORDER BY TIMESTAMP;
            """,
            reverse_sql="DROP TABLE IF EXISTS myr1_HFData_sonic;",
        ),
    ]
