# Generated by Django 6.0 on 2026-07-16

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0010_myr1hfdatasonic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myr1HfdataMerged',
            fields=[
                ('timestamp', clickhouse_backend.models.DateTime64Field(db_column='TIMESTAMP', precision=3, primary_key=True, serialize=False)),
                ('ts', clickhouse_backend.models.Float64Field(db_column='Ts')),
                ('ux', clickhouse_backend.models.Float64Field(db_column='Ux')),
                ('uy', clickhouse_backend.models.Float64Field(db_column='Uy')),
                ('uz', clickhouse_backend.models.Float64Field(db_column='Uz')),
                ('h2o', clickhouse_backend.models.Float64Field(db_column='H2O')),
                ('h2o_dry', clickhouse_backend.models.Float64Field(db_column='H2O_dry')),
                ('co2', clickhouse_backend.models.Float64Field(db_column='CO2')),
                ('co2_dry', clickhouse_backend.models.Float64Field(db_column='CO2_dry')),
                ('t_in', clickhouse_backend.models.Float64Field(db_column='T_in')),
                ('t_out', clickhouse_backend.models.Float64Field(db_column='T_out')),
                ('ptotal', clickhouse_backend.models.Float64Field(db_column='Ptotal')),
                ('agc', clickhouse_backend.models.Float64Field(db_column='AGC')),
                ('ch4_mmol_m3', clickhouse_backend.models.Float64Field(db_column='CH4_mmol_m3')),
                ('ch4_umol_mol', clickhouse_backend.models.Float64Field(db_column='CH4_umol_mol')),
                ('ch4_temperature', clickhouse_backend.models.Float64Field(db_column='CH4_Temperature')),
                ('ch4_pressure', clickhouse_backend.models.Float64Field(db_column='CH4_Pressure')),
                ('ch4_signal_strength', clickhouse_backend.models.Float64Field(db_column='CH4_Signal_Strength')),
            ],
            options={
                'db_table': 'myr1_HFData_merged',
                'managed': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW myr1_HFData_merged AS
            SELECT
                m.TIMESTAMP,
                if(s.Ts IS NOT NULL, s.Ts, m.Ts) AS Ts,
                if(s.Ux IS NOT NULL, s.Ux, m.Ux) AS Ux,
                if(s.Uy IS NOT NULL, s.Uy, m.Uy) AS Uy,
                if(s.Uz IS NOT NULL, s.Uz, m.Uz) AS Uz,
                m.H2O,
                m.H2O_dry,
                m.CO2,
                m.CO2_dry,
                m.T_in,
                m.T_out,
                m.Ptotal,
                m.AGC,
                m.CH4_mmol_m3,
                m.CH4_umol_mol,
                m.CH4_Temperature,
                m.CH4_Pressure,
                m.CH4_Signal_Strength
            FROM myr1_HFData AS m
            FINAL
            LEFT JOIN myr1_HFData_sonic AS s FINAL ON m.TIMESTAMP = s.TIMESTAMP;
            """,
            reverse_sql="DROP VIEW IF EXISTS myr1_HFData_merged;",
        ),
    ]
