# Generated by Django 2.2.16 on 2021-09-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(editable=False, null=True)),
                ('temperature', models.FloatField(editable=False)),
                ('temperature_qc', models.BooleanField(editable=False)),
                ('humidity', models.FloatField(editable=False)),
                ('humidity_qc', models.BooleanField(editable=False)),
                ('air_pressure', models.FloatField(editable=False)),
                ('air_pressure_qc', models.BooleanField(editable=False)),
                ('snow_depth', models.FloatField(editable=False)),
                ('snow_depth_qc', models.BooleanField(editable=False)),
                ('node', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='qc.Node')),
            ],
            options={
                'unique_together': {('node', 'time')},
            },
        ),
    ]
