# Generated by Django 2.2.16 on 2021-09-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
