# Generated by Django 3.2.5 on 2021-09-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_auto_20210902_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qc.site'),
        ),
    ]
