# Generated by Django 3.2.5 on 2021-09-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_alter_node_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='node',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='data', to='qc.node'),
        ),
    ]
