# Generated by Django 3.2.5 on 2021-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0005_alter_data_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='node',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
