import argparse
import json
import sys

import requests


if __name__ == '__main__':
    # Arguments
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='Uploads one or more CSV files as generated by Eddypro.',
        epilog=
        'Example of use:\n'
        'python eddypro_upload.py https://wsn.latice.eu <TOKEN> Finseflux <FILENAME>.csv',
    )
    parser.add_argument('baseurl',
        help='only the protocol, hostname and protocol')
    parser.add_argument('token', help='access token')
    parser.add_argument('name',
        help='identifies the dataset, will be prefixed with eddypro_')
    parser.add_argument('paths', nargs='+',
        help='one or more paths to the files to be uploaded')
    args = parser.parse_args()

    # Requests session
    session = requests.Session()
    headers = {'Authorization': f'Token {args.token}'}
    session.headers.update(headers)

    # Upload
    url = f'{args.baseurl}/api/upload/eddypro/'
    metadata = {'name': f'eddypro_{args.name}'}
    metadata = json.dumps(metadata)
    for path in args.paths:
        print(path)
        with open(path, 'rb') as f:
            files = {'data': (path, f), 'metadata': metadata}
            response = session.post(url, files=files)

        if response.status_code != 201:
            print(f'unexpected response status code: {response.status_code}')
            sys.exit(1)
