#
# See roles/django/defaults/main.yml for the available options
#

- name: "Development"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role              : "jdavid.django"
    django_pull       : false
    django_with_monit : false

    django            :
      debug           : true
      port            : 8000

    mods:
    - "mods/admin"
    - "mods/dotenv"
    - "mods/postgres"

    celery:
      queues          : celery_wsn
      workers         : 1

    postgres:
      name            : "wsn"
      user            : "wsn"
      password        : "wsn"

    supervisor:
      daemon          : false
