#
# See roles/django/defaults/main.yml for the available options
#

- name: "Travis"
  hosts: "development"
  vars_files:
  - "vars.yml"
  roles:
  - role              : "jdavid.django"
    django_debug      : false
    django_pull       : false
    django_with_nginx : false
    django_with_monit : false
    django_with_sudo  : false

    prefix            : "/home/travis/virtualenv/python3.7.5"
    virtualenv        : false

    django_database   :
      engine          : "postgres"
      name            : "wsn"
      user            : "postgres"
      password        : ""
